### ISSUE TITLE
Error received while running 'python3 -m pyhtools'

### ISSUE THREAD

**Issue by Pyperl** [dmdhrumilmistry/pyhtools#32]
`Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,

  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)

  File "/home/dub/pyhtools/pyhtools/__main__.py", line 1, in <module>
    from . UI import functions as UI

  File "/home/dub/pyhtools/pyhtools/UI/functions.py", line 1, in <module>
    from pyhtools.UI.colors import *

  File "/home/dub/pyhtools/pyhtools/UI/colors.py", line 1, in <module>
    from colorama import init, Style, Fore, Back

ModuleNotFoundError: No module named 'colorama'
`

**Comment by dmdhrumilmistry** [comment]
@Pyperl I'm closing this issue right now, you can try using below command, and if you're facing same issue, feel free to reopen it:

```bash
python3 -m pip install colorama
```
