### ISSUE TITLE
issue when I start pyhtools

### ISSUE THREAD

**Issue by flash-dady-686323** [dmdhrumilmistry/pyhtools#34]
```bash
WARNING: No route found for IPv6 destination :: (no default route?). This affects only IPv6
WARNING: can't import layer ipsec: cannot import name 'gcd' from 'fractions' (/usr/lib/python3.10/fractions.py)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/users/sixtu/desktop/pyhtools/pyhtools/__main__.py", line 1, in <module>
    from . UI import functions as UI
  File "/mnt/c/users/sixtu/desktop/pyhtools/pyhtools/UI/functions.py", line 7, in <module>
    import pyhtools.attackers.attackers as attacker
  File "/mnt/c/users/sixtu/desktop/pyhtools/pyhtools/attackers/attackers.py", line 10, in <module>
    from pyhtools.attackers.web.webdiscover import Discoverer
ModuleNotFoundError: No module named 'pyhtools.attackers.web.webdiscover'
```

**Comment by dmdhrumilmistry** [comment]
hello @flash-dady-686323, that's a import bug. I'll fix it ASAP.
